---
title: "Interactive graph examples"
author: "Alex Ehrens"
date: "10/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here, we'll practice creating some interactive graphs and tables using built in datasets in R packages.

- Interactive plots: {plotly}
- Interactive tables: {DT}

```{r, include = FALSE}
# Attach packages:
library(tidyverse)
library(plotly)
library(DT)

```

### A. Interactive graph of iris dimensions

Using Edgar Anderson's famous 'iris' dataset

```{r, echo = FALSE}

iris_graph <- ggplot(data = iris, aes(x = Petal.Width, y = Petal.Length)) +
  geom_point(aes(size = Sepal.Width,
                 color = Species),
             alpha = 0.5) +
  theme_minimal() +
  labs(x = "Petal width (cm)",
       y = "Petal length (cm)",
       title = "My Iris Graph")

### Command + Shift + C to comment out entire section
# eval = FALSE at top of code chunk so R doesn't try to evaluate chunk when knitting

# iris_graph

#### make sure static version of graph works BEFORE interactive version

ggplotly(iris_graph)

```

